runtime: nodejs16
env_variables:
  NODE_ENV: development
  DATABASE_NAME: simplifyManage
  DATABASE_USER: admin
  DATABASE_PASSWORD: mDuRXDLKxqa8SlZC
  JWT_SECRET: My name is Kunga Tashi and I want this project to be really successful.
  JWT_EXPIRES_IN: 30d
